name: Copy Secrets to GCP

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  copy-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions-brcm/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

#      - name: Install Google Cloud SDK
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y apt-transport-https ca-certificates gnupg
#          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
#          sudo apt-get install -y google-cloud-sdk

      - name: Copy GitHub Secrets to GCP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          #!/bin/bash

          # Set variables
          GITHUB_API_URL="https://github.gwd.broadcom.net"
          REPO_OWNER="TNZ"
          REPO_NAME="hy036913-test"
#          GCP_PROJECT_ID=""

          # Authenticate with Google Cloud
#          echo "$GCP_SA_KEY" > gcloud-service-key.json
#          gcloud auth activate-service-account --key-file=gcloud-service-key.json
#          gcloud config set project "$GCP_PROJECT_ID"

          # Fetch GitHub secrets
          fetch_github_secrets() {
            secrets_url="$GITHUB_API_URL/repos/$REPO_OWNER/$REPO_NAME/actions/secrets"
            response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$secrets_url")
            echo "$response" | jq -r '.secrets[] | {name: .name}'
          }

          # Upload secrets to GCP Secret Manager
#          upload_secret_to_gcp() {
#            secret_name="$1"
#            secret_value="$2"
#
#            # Create the secret if it doesn't exist
#            if ! gcloud secrets describe "$secret_name" --project "$GCP_PROJECT_ID" > /dev/null 2>&1; then
#              gcloud secrets create "$secret_name" --replication-policy="automatic" --project="$GCP_PROJECT_ID"
#            fi
#
#            # Add a new version to the secret
#            echo -n "$secret_value" | gcloud secrets versions add "$secret_name" --data-file=- --project="$GCP_PROJECT_ID"
#            echo "Uploaded secret: $secret_name"
#          }

          # Main logic
          secrets=$(fetch_github_secrets)

          echo "$secrets" | while read -r secret; do
            secret_name=$(echo "$secret" | jq -r '.name')
            echo "$secret_name"
            secret_value=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "$GITHUB_API_URL/repos/$REPO_OWNER/$REPO_NAME/actions/secrets/$secret_name" | jq -r '.value')

#            if [[ -n "$secret_value" ]]; then
#              upload_secret_to_gcp "$secret_name" "$secret_value"
#            fi
          done

          # Clean up
#          rm gcloud-service-key.json
