name: Copy Secrets to GCP

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  copy-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Copy GitHub Secrets to GCP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash

          # Set variables
          GITHUB_API_URL="https://api.github.com"
          REPO_OWNER="yharish991"
          REPO_NAME="hy036913-test"

          # Fetch GitHub secrets
          fetch_github_secrets() {
            secrets_url="$GITHUB_API_URL/repos/$REPO_OWNER/$REPO_NAME/actions/secrets"
            response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$secrets_url")
            echo "$response" | jq -r '.secrets[] | {name: .name}'
          }

          # Main logic
          secrets=$(fetch_github_secrets)

          echo "$secrets" | while read -r secret; do
            secret_name=$(echo "$secret" | jq -r '.name')
            echo "$secret_name"
            secret_value=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "$GITHUB_API_URL/repos/$REPO_OWNER/$REPO_NAME/actions/secrets/$secret_name" | jq -r '.value')

          done

          # Clean up
